// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbctakgiuscgakerljpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiY3Rha2dpdXNjZ2FrZXJsanBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjA3MzMsImV4cCI6MjA3NDM5NjczM30.a8MBZVWwVY4wt5LeDu9KOlpeWRqwi_bLDkfxxSmx_jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});